[package]
name = "yaks"
version = "0.0.0-alpha1"
authors = ["Alexander Sepity <alexander.sepity@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
repository = "https://github.com/Ratysz/yaks"
readme = "README.md"
keywords = ["ecs", "entity", "component"]
categories = ["data-structures", "game-engines"]

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
#fixedbitset = { version = "0.2.0", default-features = false }
fxhash = "0.2.1"
#hecs = { git = "https://github.com/Ralith/hecs.git", rev = "6b9c11b47bf98d94cda6f4b3d3c3207bbb7f4439" }
hecs = "0.2.7"
paste = "0.1.6"
#petgraph = "0.5.0"
resources = "0.2.1"
#scoped_threadpool = "0.1.9"