[package]
name = "yaks"
version = "0.1.0-alpha.0"
description = "A minimalistic ECS."
authors = ["Alexander Sepity <alexander.sepity@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
repository = "https://github.com/Ratysz/yaks"
readme = "README.md"
keywords = ["ecs", "entity", "component"]
categories = ["data-structures", "game-engines"]

[badges]
maintenance = { status = "actively-developed" }

[features]
macros = ["hecs/macros"]
parallel = []
impl_scoped_threadpool = ["scoped_threadpool"]

[dependencies]
#fixedbitset = { version = "0.2.0", default-features = false }
fixedbitset = "0.2.0"
fxhash = "0.2.1"
#hecs = { git = "https://github.com/Ralith/hecs.git", rev = "a09e023359718a4028dc8539aa7c823005b0ff5b" }
hecs = "0.2.7"
paste = "0.1.6"
resources = "0.2.1"
scoped_threadpool = { version = "0.1.9", optional = true }